name: package build linux

on:
  workflow_dispatch:
    branches:
    - master

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        name: [
          linux-x86_64
        ]
        include:
          - name: linux-x86_64
            os: ubuntu-20.04
            arch: x86_64
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: build linux outputs
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          libxcb1-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          libgtk-3-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxcb-*-dev \
          libclang-11-dev \
          libclang-12-dev \
          llvm-12
        apt list --installed
        make ARCH=${{ matrix.arch }}
        echo UPLOAD_FILE=cutter-deps-qt-linux-${{ matrix.arch }}.tar.gz >> $GITHUB_ENV
        echo UPLOAD_ASSET_TYPE=application/gzip >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      if: startsWith(github.event.ref, 'refs/tags') == false
      with:
        name: ${{ env.UPLOAD_FILE }}
        path: ${{ env.UPLOAD_FILE }}
        if-no-files-found: warn
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: ${{ env.UPLOAD_ASSET_TYPE }}
